# Generated by Django 3.0.4 on 2026-06-02 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0021_auto_20210326_2023'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='price',
            field=models.FloatField(help_text='Price of the item in Ksh'),
        ),
        migrations.AlterField(
            model_name='item',
            name='slug',
            field=models.SlugField(default='sushi_name', unique=True),
        ),
        migrations.AlterField(
            model_name='item',
            name='title',
            field=models.CharField(help_text='Name of the menu item', max_length=150),
        ),
        migrations.AlterField(
            model_name='reviews',
            name='review',
            field=models.TextField(help_text="Customer's review text"),
        ),
        migrations.AlterField(
            model_name='reviews',
            name='rslug',
            field=models.SlugField(help_text='Slug reference to the reviewed item'),
        ),
    ]
